package:
  name: pscondaenvs
  version: "{{ environ.get('GIT_DESCRIBE_TAG') }}"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  run:
    - conda >=4.1

source:
  path: ./

about:
  home: https://github.com/BCSharp/PSCondaEnvs
  license: MIT
  license_file: LICENSE
  summary: Quickly and easily add `activate` and `deactivate` support to your Powershell console.  Just do `conda install -n root -c pscondaenvs pscondaenvs`.
